const LIST_FILTER_ALL = `LIST_FILTER_ALL`;
const LIST_FILTER_COMPLETED = `LIST_FILTER_COMPLETED`;
const LIST_FILTER_NON_COMPLETED = `LIST_FILTER_NON_COMPLETED`;

export {LIST_FILTER_ALL, LIST_FILTER_COMPLETED, LIST_FILTER_NON_COMPLETED}